services:
  mysql:
    image: mysql:8.0.33
    container_name: marketplace-mysql
    environment:
      MYSQL_DATABASE: marketplace
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 10s
      retries: 10
    networks:
      shared_network:
        aliases:
          - marketplace-db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: marketplace-app
    hostname: laravel-backend
    volumes:
      - .:/var/www/html
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=marketplace
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - APP_URL=http://laravel-backend:8000
      - FRONTEND_URL=http://nextjs-frontend:3000
    networks:
      shared_network:
        aliases:
          - laravel-backend

  webserver:
    image: nginx:alpine
    container_name: marketplace-webserver
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      shared_network:

  composer:
    image: composer:2
    container_name: marketplace-composer
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    networks:
      shared_network:

volumes:
  mysql_data:

networks:
  shared_network:
    name: marketplace_network
    driver: bridge